
import { Inter, EB_Garamond } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";





const inter =  Inter ({ subsets: ["latin"] });

export const metadata = { 
  title: "lansarcenter-academy",
  description: "Generated by lansarcenter",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider> 
    <html lang="en">
      <body className={inter.className}>{children}
     <Toaster/>
     
   </body>
    </html>
    </ClerkProvider>
  );
}
